### PR TITLE
Add airlines

### PR DESCRIPTION
**Pull request by TomWFox**
work in progress...

Not an exhaustive list but most of the biggest / most well known - I tried adding Ryanair but for some reason it wouldn't load the widget 🤷‍♂️

### CODE REVIEW

**Comment by xdamman** [comment]
That's great! Thanks for contributing. I cannot merge it until it's a draft. Can you post this PR? 
And let's definitely add Ryanair http://facebook.com/ryanair

**Comment by TomWFox** [comment]
I puzzled over Ryanair for a bit but I can't figure it out.

I had the code below which follows the same format as the rest but it just wouldn't load...
```
<iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Fryanair%2F&tabs&width=340&height=150&small_header=true&adapt_container_width=true&hide_cover=true&show_facepile=true&appId=110203902358957" width="340" height="150" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>
```

**Comment by TomWFox** [comment]
Tested on the social plugin page - https://developers.facebook.com/docs/plugins/page-plugin
and it also didn't work - maybe its due to the configuration of the page - privacy settings maybe?

**Comment by xdamman** [comment]
Ah could be. Good catch. Well, let’s already publish this then. Thank you!

**Pull request merged**
