### PR TITLE
Add Twitter links

### PR DESCRIPTION
**Pull request by jlevers**
I added Twitter links to the homepage, in a separate tab from the Facebook links, so that people can see the links for each company separately.

Twitter only provides a very simplistic "Follow @<name>" embeddable widget, and the widget renders an `<iframe>` in place of the `<a>` tag that they give you to embed in your page, so it's difficult to modify the widget to say "Unfollow" instead of "Follow".

If you'd like me to change anything else about this, let me know! Styling isn't my strong suit, so I'm very open to stylistic changes/suggestions.

### CODE REVIEW

**Comment by xdamman** [comment]
Thanks for contributing.

I'm not a big fan of this user experience though. It almost feels like we are promoting them. Not your fault, just the twitter widget that is not great for this.

What about instead creating a twitter list of those accounts and linking to it?

**Comment by jlevers** [comment]
Yeah, good point -- it does feel like a somewhat backwards way of presenting the information we're trying to present. I'll make a Twitter list.

(I was thinking about making my own Twitter widget that _would_ say "Unfollow" when the user is already following an account, but the roadblock I'm running into is that to determine whether or not someone is following a given Twitter account requires them to login and approve the widget ahead of time, which defeats the purpose.)

**Comment by xdamman** [comment]
Well, you could enter a twitter username (e.g. [@xdamman](https://twitter.com/xdamman)) and then through the public API that doesn’t require oauth, look at all the people I follow and match that with the twitter list of the largest CO2 emitters.

As a bonus, you could look at all the people that I follow and/or that follow me and compare that list.

Definitely much more work than a simple HTML page though for sure!

**Comment by TomWFox** [comment]
It's still not an ideal solution but you could have a widget like below from shields.io...
```
<a href="https://twitter.com/intent/follow?screen_name=audi"><img alt="Unfollow Audi" src="https://img.shields.io/twitter/follow/audi?style=social&label=Unfollow%20Audi"></a>
```

looks like...

<a href="https://twitter.com/intent/follow?screen_name=audi">Unfollow Audi</a>

But it doesn't show whether you are following them or not.

**Comment by rmdes** [comment]
> It's still not an ideal solution but you could have a widget like below from shields.io...
> 
> ```
> <a href="https://twitter.com/intent/follow?screen_name=audi">Unfollow Audi</a>
> ```
> 
> looks like...
> 
> [Unfollow Audi](https://twitter.com/intent/follow?screen_name=audi)
> 
> But it doesn't show whether you are following them or not.

You would need to have the user to auth first to know that right ?
would it be a problem to have twitter/facebook login ?

**Comment by jlevers** [comment]
I added Twitter lists for both the car manufacturers and the airlines.

After thinking about it some more, I actually think Twitter lists are a better solution here than giving people a personalized list of accounts to unfollow based on their Twitter handle, for two reasons:
 * Requiring people to enter their Twitter handle into an unknown website might be off-putting
 * It wouldn't actually be faster for the user -- for every Unfollow button on our page that they click, a separate window pops up. With a Twitter list, all the people they need to unfollow are on a single page, and they can do all the following/unfollowing from that page.

If any of you disagree with my reasoning there, please let me know!

(Edit: accidentally posted this comment before I was done writing it)

**Comment by xdamman** [comment]
Thanks! I've updated it a bit to use the tabs to separate sections:

**Comment by jlevers** [comment]
Ah yeah, that's definitely a better layout. Cheers man!

**Pull request merged**
